# Generated by Django 3.2.25 on 2025-04-25 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('status', models.CharField(max_length=50, verbose_name='检测状态')),
                ('details', models.TextField(blank=True, verbose_name='详细信息')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domain', verbose_name='监控对象')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '检测日志',
                'verbose_name_plural': '检测日志',
                'db_table': 'check_log',
            },
        ),
        migrations.CreateModel(
            name='MonitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('status', models.CharField(default='', max_length=50, verbose_name='访问状态')),
                ('total_time', models.FloatField(null=True, verbose_name='总时间(秒)')),
                ('dns_time', models.FloatField(null=True, verbose_name='解析时间(秒)')),
                ('details', models.TextField(blank=True, verbose_name='详细信息')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domain', verbose_name='监控对象')),
            ],
            options={
                'verbose_name': '监控记录',
                'verbose_name_plural': '监控记录',
                'db_table': 'monitor_records',
            },
        ),
        migrations.DeleteModel(
            name='WebsiteMonitorResult',
        ),
    ]
