# Generated by Django 3.2.25 on 2025-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_domain_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='alert_threshold',
            field=models.IntegerField(default=3, verbose_name='异常连续次数'),
        ),
        migrations.AddField(
            model_name='domain',
            name='check_unreachable',
            field=models.BooleanField(default=True, verbose_name='监控URL无法访问'),
        ),
        migrations.AddField(
            model_name='domain',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='任务结束时间'),
        ),
        migrations.AddField(
            model_name='domain',
            name='long_term_monitor',
            field=models.BooleanField(default=True, verbose_name='长期监控'),
        ),
        migrations.AddField(
            model_name='domain',
            name='notify_email',
            field=models.BooleanField(default=False, verbose_name='邮箱通知'),
        ),
        migrations.AddField(
            model_name='domain',
            name='notify_inbox',
            field=models.BooleanField(default=False, verbose_name='站内信通知'),
        ),
        migrations.AddField(
            model_name='domain',
            name='notify_telegram',
            field=models.BooleanField(default=False, verbose_name='Telegram通知'),
        ),
        migrations.AddField(
            model_name='domain',
            name='response_time_threshold',
            field=models.IntegerField(default=1000, verbose_name='响应时间阈值（毫秒）'),
        ),
    ]
