# Generated by Django 3.2.25 on 2025-04-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250419_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='check_unreachable',
        ),
    ]
