# Generated by Django 3.2.25 on 2025-04-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_domain_check_unreachable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='check_cert',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='check_domain',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='check_https',
        ),
        migrations.AddField(
            model_name='domain',
            name='monitor_type',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='https', max_length=5, verbose_name='监控类型'),
        ),
        migrations.AddField(
            model_name='domain',
            name='request_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=4, verbose_name='请求方式'),
        ),
    ]
