# Generated by Django 3.2.25 on 2025-04-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250425_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': '监控对象', 'verbose_name_plural': '监控对象'},
        ),
        migrations.AlterModelOptions(
            name='websitemonitorresult',
            options={'verbose_name': '监控日志', 'verbose_name_plural': '监控日志'},
        ),
        migrations.AlterModelTable(
            name='domain',
            table='monitors',
        ),
        migrations.AlterModelTable(
            name='websitemonitorresult',
            table='monitor_logs',
        ),
    ]
